stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - params.yaml
    params:
      - split_data.test_size
      - split_data.random_state
      - data_ingestion.batch_size
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/interim/train_processed.csv     # ← explicit & recommended
      - data/interim/test_processed.csv      # ← explicit & recommended
      # or (if you prefer to track the whole folder):
      # - data/interim

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/interim/train_processed.csv
      - params.yaml
    params:
      - model_building.max_depth
      - model_building.n_estimators
      - model_building.max_features
      - model_building.learning_rate
      - model_building.ngrams_range
    outs:
      - lgbm_model.pkl
      - tfidf_vectorizer.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - lgbm_model.pkl
      - tfidf_vectorizer.pkl
      - data/interim/test_processed.csv
      - data/interim/train_processed.csv
      - params.yaml
    outs:
      - experiment_info.json
  register_model:
    cmd: python src/model/register_model.py
    deps:
      - src/model/register_model.py
      - experiment_info.json
    