# Data Ingestion Configuration
data_ingestion:
  data_url: "https://raw.githubusercontent.com/Himanshu-1703/reddit-sentiment-analysis/refs/heads/main/data/reddit.csv"
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  batch_size: 1000

# Data Splitting Configuration
split_data:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  stratify_column: null  # Set to column name if you want stratified split

# Preprocessing Configuration
preprocessing:
  text_column: "clean_comment"
  target_column: "category"
  lowercase: true
  remove_punctuation: true
  remove_stopwords: true
  min_text_length: 3

# Feature Engineering Configuration
feature_engineering:
  vectorizer: "tfidf"
  ngram_range: [1, 3]
  max_features: 1000
  min_df: 2
  max_df: 0.95

# Model Training Configuration
model_training:
  model_type: "xgboost"
  learning_rate: 0.09
  max_depth: 20
  n_estimators: 367
  early_stopping_rounds: 10
  eval_metric: "mlogloss"

# Model Evaluation Configuration
evaluation:
  metrics: ["accuracy", "f1_score", "precision", "recall"]
  confusion_matrix: true
  classification_report: true